DonationApp.Web/Models/Donater.cs
using DonationApp.Web.Core;
using System;
using System.ComponentModel.DataAnnotations;

namespace DonationApp.Web.Models
{
    public class Donater
    {
        //public int Id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Укажите имя")]
        [StringLength(30, ErrorMessage = "Имя должно не меньше 2 и не более 30 символов.", MinimumLength = 2)]
        [Display(Name="Имя")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Укажите электронную почту")]
        [RegularExpression("^([\\w\\.\\-]+)@([\\w\\-]+)((\\.(\\w){2,3})+)$", ErrorMessage = "Не корректный е-мэйл")]
        [Display(Name = "Е-мэйл")]
        public string Email { get; set; }

        [Display(Name = "Комментарий")]
        public string Comment { get; set; }

        [Required(ErrorMessage = "Укажите вид платежа")]
        [Display(Name="Вид платежа")]
        public PaymentType Payment { get; set; }

        [Required(ErrorMessage = "Укажите объем платежа")]
        [Display(Name = "Количество")]
        [RegularExpression("^\\d*\\.?\\d*$", ErrorMessage = "Введите число")]
        public decimal Amount { get; set; } = 0;

        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name ="Дата платежа")]
        public DateTime Date { get; set; } = DateTime.Now;
    }
}

DonationApp.Web/Models/ErrorViewModel.cs
using System;

namespace DonationApp.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DonationApp.Web/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace DonationApp.Web.Models
{
    public class User
    {
        [Display(Name = "Логин")]
        [Required(ErrorMessage = "Заполните поле логин")]
        public string Login { get; set; }

        [Display(Name = "Пароль")]
        [Required(ErrorMessage = "Заполните поле пароль")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

DonationApp.Web/Controllers/AdminController.cs
using DonationApp.Web.Core;
using DonationApp.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace DonationApp.Web.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LoginUser([FromForm] User user)
        {
            if(ModelState.IsValid)
            {
                if(user.Login.Trim().ToLower() == "admin" && user.Password == "admin")
                {
                    return View("Statistic", Repository.Donaters);
                }
                else
                {
                    return View("AccessDenied");
                }
            }
            return View(nameof(Index));
        }
    }
}

DonationApp.Web/Controllers/DonateController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using DonationApp.Web.Models;
using DonationApp.Web.Core;

namespace DonationApp.Web.Controllers
{
    public class DonateController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create([FromForm] Donater donater)
        {
            if(donater == null)
            {
                return View();
            }

            Repository.AddDonater(donater);

            if(EmailSender.SendEmail(donater))
            {
                return View("CompletePayment", donater);
            }

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DonationApp.Web/Controllers/HomeController.cs
using DonationApp.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DonationApp.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DonationApp.Web/Views/Admin/AccessDenied.cshtml
<h4>В доступе отказано</h4>
<div class="alert alert-danger" role="alert">
  У вас нет прав для просмотра статистики. Проверьте логин и пароль и перелогиньтесь.
</div>

<div class="mt-5">
    <a asp-controller="admin" asp-action="Index">Назад</a>
</div>

DonationApp.Web/Views/Admin/Index.cshtml
@model DonationApp.Web.Models.User

<h4>Форма логина</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="LoginUser" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Залогиниться" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-controller="Donate" asp-action="Index">На главную</a>
</div>

DonationApp.Web/Views/Admin/Statistic.cshtml
@model IEnumerable<DonationApp.Web.Models.Donater>
@using DonationApp.Web.Core

@{
    ViewData["Title"] = "Statistic";
}

<h1>Статистика</h1>

<table class="table">
    <thead class="table-light">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Payment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr class="text-secondary">
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Payment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount) $
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
        </tr>
}
    </tbody>
    <tfoot>
        <tr>
            <td class="fw-bold fs-3">Итого</td>
            <td></td>
            <td></td>
            <td></td>
            <td class="fw-bold fs-3">@Repository.AllSumOfDotanions() $</td>
            <td></td>
        </tr>
    </tfoot>
</table>

DonationApp.Web/Views/Donate/CompletePayment.cshtml
@model DonationApp.Web.Models.Donater

<h4>Успешное проведение платежа</h4>

<div class="alert alert-success" role="alert">
  Большое спасибо @Model.Name ваши деньги пойдут по назначению.
  Мы также отправили вам на почту письмо с подтверждением платежа.
</div>

<div class="mt-5">
    <a asp-controller="Donate" asp-action="Index">На главную</a>
</div>

DonationApp.Web/Views/Donate/Create.cshtml
@using DonationApp.Web.Core
@model DonationApp.Web.Models.Donater

@{
    ViewData["Title"] = "Create";
}

<h4>UserDonater</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Payment" class="control-label"></label>
                <select asp-for="Payment" asp-items="Html.GetEnumSelectList<PaymentType>()" class="form-control">
                    <option disabled selected>Выберите платеж</option>
                </select>
                <span asp-validation-for="Payment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Оплатить" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-danger">Отмена</a>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">На главную</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DonationApp.Web/Views/Donate/Index.cshtml
<div>
    <h1>Пожертвование голодающим</h1>
    <a class="btn btn-success" asp-area="" asp-controller="Donate" asp-action="Create">Пожертвовать</a>
</div>

DonationApp.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DonationApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DonationApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Donate" asp-action="Index">Donater</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Donate" asp-action="Index">Пожертвовать</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Статистика</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DonationApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>